### ISSUE TITLE
Location is not intuitive

### ISSUE THREAD

**Issue by R2D221** [joaquingatica/Notie-Imberisseo#1]
Having to set the location manually (writing the name of country and city) is not intuitive, and it can easily lead to errors (e.g. misspelling it or writing it in other language).
I suggest using combo boxes that have all locations predefined (or downloadable via internet, whatever is easier); or even including a map, but that's more difficult to implement.
Also, location should be guessed based on the timezone (my timezone is America/Mexico_City, but the location is set to Montevideo, Uruguay).

**Comment by joaquingatica** [comment]
Thanks for the feedback! Now that you mention it, you're completely right. I'll put it in the improvements queue. The idea of guessing from the timezone is a good one! So simple, and nevertheless it never crossed my mind hehe. Hantanyel ar namárië!

**Comment by joaquingatica** [comment]
@R2D221 I had this project a bit abandoned for some years, but I'm back now, my apologies.

Would you mind trying this [latest release](https://github.com/joaquingatica/Notie-Imberisseo/releases/tag/v2.6.0-rc) to see if it works for you?

I didn't change to dropdown, but did these 2 enhancements:
* Calculate City and Country based on the user's computer IP address
* Calculate Time Zone automatically bases on country and city

Hope this works for you! If you find an error or can't make it work, let me know, since this is a pre-release (Release Candidate).

Thanks!
